
CREATE DATABASE [ChatBotUMG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ChatBotUMG', FILENAME = N'/var/opt/mssql/data/ChatBotUMG.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ChatBotUMG_log', FILENAME = N'/var/opt/mssql/data/ChatBotUMG_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ChatBotUMG] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ChatBotUMG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ChatBotUMG] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ChatBotUMG] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ChatBotUMG] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ChatBotUMG] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ChatBotUMG] SET ARITHABORT OFF 
GO
ALTER DATABASE [ChatBotUMG] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ChatBotUMG] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ChatBotUMG] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ChatBotUMG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ChatBotUMG] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ChatBotUMG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ChatBotUMG] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ChatBotUMG] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ChatBotUMG] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ChatBotUMG] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ChatBotUMG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ChatBotUMG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ChatBotUMG] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ChatBotUMG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ChatBotUMG] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ChatBotUMG] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ChatBotUMG] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ChatBotUMG] SET RECOVERY FULL 
GO
ALTER DATABASE [ChatBotUMG] SET  MULTI_USER 
GO
ALTER DATABASE [ChatBotUMG] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ChatBotUMG] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ChatBotUMG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ChatBotUMG] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ChatBotUMG] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ChatBotUMG] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ChatBotUMG', N'ON'
GO
ALTER DATABASE [ChatBotUMG] SET QUERY_STORE = ON
GO
ALTER DATABASE [ChatBotUMG] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ChatBotUMG]
GO
/****** Object:  Table [dbo].[estado_usuarios_telegram]    Script Date: 09/06/2025 10:53:16 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[estado_usuarios_telegram](
	[chat_id] [bigint] NOT NULL,
	[estado] [nvarchar](50) NULL,
	[producto_buscado] [nvarchar](255) NULL,
	[ultima_interaccion] [datetime] NULL,
	[estado_codigo] [int] NULL,
	[imagenes_procesadas] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[chat_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[estado_usuarios_telegram] ADD  DEFAULT (getdate()) FOR [ultima_interaccion]
GO
ALTER TABLE [dbo].[estado_usuarios_telegram] ADD  DEFAULT ((0)) FOR [estado_codigo]
GO
ALTER TABLE [dbo].[estado_usuarios_telegram] ADD  DEFAULT ((0)) FOR [imagenes_procesadas]
GO
USE [master]
GO
ALTER DATABASE [ChatBotUMG] SET  READ_WRITE 
GO
